version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "Robert-96"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    assignees:
      - "Robert-96"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    assignees:
      - "Robert-96"
    schedule:
      interval: "weekly"
